package clientWS.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-09-04T23:03:20.294-05:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "SumWSServiceImplService",
                  wsdlLocation = "http://localhost:8080//SumWSServiceImplService/SumWSServiceImpl?wsdl",
                  targetNamespace = "http://beans/")
public class SumWSServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://beans/", "SumWSServiceImplService");
    public static final QName SumWSServiceImplPort = new QName("http://beans/", "SumWSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080//SumWSServiceImplService/SumWSServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SumWSServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080//SumWSServiceImplService/SumWSServiceImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SumWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SumWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumWSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SumWSServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SumWSServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SumWSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SumWSService
     */
    @WebEndpoint(name = "SumWSServiceImplPort")
    public SumWSService getSumWSServiceImplPort() {
        return super.getPort(SumWSServiceImplPort, SumWSService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SumWSService
     */
    @WebEndpoint(name = "SumWSServiceImplPort")
    public SumWSService getSumWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SumWSServiceImplPort, SumWSService.class, features);
    }

}
