package clientWS.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-09-04T23:03:20.227-05:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://beans/", name = "SumWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface SumWSService {

    @WebMethod
    @Action(input = "http://beans/SumWSService/sumRequest", output = "http://beans/SumWSService/sumResponse")
    @RequestWrapper(localName = "sum", targetNamespace = "http://beans/", className = "clientWS.service.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://beans/", className = "clientWS.service.SumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sum(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
