package clientWS.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-09-09T22:09:57.023-05:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://interfaces.services/", name = "PersonServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonServiceWs {

    @WebMethod
    @Action(input = "http://interfaces.services/PersonServiceWs/getAllPersonsRequest", output = "http://interfaces.services/PersonServiceWs/getAllPersonsResponse")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://interfaces.services/", className = "clientWS.service.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://interfaces.services/", className = "clientWS.service.GetAllPersonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<clientWS.service.Person> getAllPersons()
;
}
